### ISSUE TITLE
Warts

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcppsmc#14]
Running `R CMD check --as-cran` under r-devel, which is easily doable by
- submitting to [win-builder](https://win-builder.r-project.org/)
- submitting to the (awesome) [R Hub](https://builder.r-hub.io/) (which I prefer via the corresponding R package from GitHub allowing command-line access)
- setting up R-devel locally, for example using the [Docker container](https://hub.docker.com/r/rocker/drd/) or compiling locally

gets us

```
* checking R code for possible problems ... NOTE
Found the following calls to data() loading into the global environment:
File ‘RcppSMC/R/LinReg.R’:
  data(radiata)
File ‘RcppSMC/R/LinRegLA.R’:
  data(radiata)
See section ‘Good practice’ in ‘?data’.
* checking Rd files ... OK
```

and

```
* checking compiled code ... NOTE
File ‘RcppSMC/libs/RcppSMC.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’

It is good practice to register native routines and to disable symbol search.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
* checking examples ... OK
```

I will deal with the registration aspect.  @LeahPrice can you please make `data()` use conformant?

**Comment by eddelbuettel** [comment]
Registration was taken care of before, and was fixed now by re-running `compileAttributes()` (twice, due to a one-off transition with Rcpp 0.12.12 in response to R 3.4.*).  This requires the current version of Rcpp.

Now committed.

**Comment by adamjohansen** [comment]
Thanks! I had a feeling you'd be an expert on that one...

**Comment by LeahPrice** [comment]
Thanks for fixing up that registration issue. That is cool how R Hub lets you do checks on other platforms from the command line. The checks seemed to go well so I've done a pull request for this and the NEWS update.

**Comment by eddelbuettel** [comment]
Checking cleanly now...
