### ISSUE TITLE
Parameter Object and Adaptation

### ISSUE THREAD

**Issue by LeahPrice** [eddelbuettel/rcppsmc#16]
The next couple of planned pull requests are about making it easier to keep track of and adapt additional algorithm parameters. This is useful in general and it is especially important when using SMC to perform inference on static Bayesian models. In this pull request, I'd like to make the necessary changes to the existing library:

* Adding a template parameter for the algorithm parameters to the sampler object
* Creating a base class for adaptation

My plan is to give the examples in a separate pull request.

**Comment by adamjohansen** [comment]
This seems sensible to me.

If I interpret this correctly, the additional template parameter will break backward compatibility; that should be clearly signposted in the associated docs.

**Comment by LeahPrice** [comment]
I've set it up so that there is a empty class as the default template parameter, so fortunately it shouldn't break backwards compatibility.

**Comment by adamjohansen** [comment]
Oh, great -- I'd forgotten where we'd ended up after all those discussions. I should have checked...
