### ISSUE TITLE
Adaptation for static Bayesian models

### ISSUE THREAD

**Issue by LeahPrice** [eddelbuettel/rcppsmc#17]
Following on from the previous issue ticket (#16), the plan in this pull request is to make some of the more common methods for parameter adaptation for static Bayesian models available. Specifically,
* Estimating the covariance matrix from the population of particles (e.g. for use in an MCMC proposal)
* Adapting the 'temperature' schedule in likelihood annealing SMC
* Adapting the number of MCMC repeats

**Comment by adamjohansen** [comment]
I'm certainly in favour of this, but these do seem to be two distinct things: I'd make sure that generic code for facilitating adaptation is clearly distinguished from the specific example. The former is likely to be reused in other places and we want it to be clear to users that this is the intention.

I can see the logic in separating the examples from the base code changes and personally I'd always err on the side of more, smaller commits/pulls, there's not much cost associated with them and there can be significant advantages.

**Comment by LeahPrice** [comment]
Okay, I'd be happy to do the commits for these two things separately. I'll edit my original issue ticket and add another.
