### ISSUE TITLE
Plan for remainder of GSoC 

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcppsmc#6]
@LeahPrice I might be beneficial if we all were on the same page with respect to remaining and forthcoming code changes.  I would prefer us to not play "small ball" (as they say in the States) but to keep bigger open issues in mind.   Can you maybe edit this box (and remove these opening lines) to fill in what folllows?   We can then (literally) tick these off.

 - [ ] Item 1 to do abc
 - [ ] Item 2 to do def
 - [ ] Item 3 to do ghi

**Comment by LeahPrice** [comment]
It looks like I don't have write access to your repository so I've written my plan below.

Here's my list of things that are done and just need to be moved across.  I chose this order based mostly on what I think will require the least amount of repeated work and reviewing.
- [x] Switching to a population level object and updating ToDo
- [x] Updating example namespaces and removing rngR
- [ ] Adding log evidence estimation capabilities (standard SMC estimator and path sampling estimators)
- [ ] Getting Roxygen comments to produce .Rd files and making data a component of the package
- [ ] Add linear regression examples with data and likelihood annealing (without adaptation)
- [ ] Add particle marginal Metropolis Hastings example
- [ ] Parameter adaptation and an adapted version of linear regression example (almost finalized)

Other plans:
- [ ] Auxiliary particle filter example
- [ ] Creating vignette(s)
- [ ] Arma::mat version of the particle values
- [ ] Storing ancestral lines of particles
- [ ] Iterated auxiliary particle filter

I'd be happy to alter any of this if you have suggestions.

**Comment by eddelbuettel** [comment]
@LeahPrice I just edited the above and moved the Roxygen issue to "maybe if time remains".  Let's try to focus on more important methodological contributions where I quite like the list above.

Can we maybe to the (common for some projects) scheme of
- 'propose changes first' (ie: issue ticket), 
- 'get consensus' 
- submit code for review.

**Comment by eddelbuettel** [comment]
We can close this one as we moved along well.
